### ISSUE TITLE
Include Announcements in the configuation options

### ISSUE THREAD

**Issue by hilongo** [pkp/textEditorExtras#10]
It would be very useful if the Announcements option could be included in the plugin configuration to enable the extra buttons there too.

![902f27c68d47898cb13e5fd88089b1c6b65d29c5](https://user-images.githubusercontent.com/497232/119188423-068db680-ba51-11eb-811c-b2a9fde6803e.png)

**Comment by NateWr** [comment]
Hi @hilongo, I've added support for the announcements and released a new version of the plugin (1.0.0.4). It should be added to the plugin gallery soon: https://github.com/pkp/plugin-gallery/pull/85.
