### ISSUE TITLE
enable fullscreen mode

### ISSUE THREAD

**Issue by felixhelix** [pkp/textEditorExtras#12]
Hi,

I try to get the fullscreen mode enabled for tinyMCE. The mode is available i.e. for the discussion message field. 
However, if I add the toolbar button and plugin by extending the textEditorExtras, the option doesn't show up. There is no error message also. The same happens if I add the option directly in the code i.e. for the journals's masthead "editorial team" field.
Any ideas?

I experience this with OJS 3.3.0.7.  and OJS 3.3.0.8. 

your's
Felix

**Comment by NateWr** [comment]
@felixhelix if you open a PR with the changes you have tried, I'll test them locally and see if I can find the source of the problem.

**Comment by felixhelix** [comment]
Thank's @NateWr , that would be great!
https://github.com/pkp/textEditorExtras/pull/13

**Comment by NateWr** [comment]
Thanks @felixhelix. Your setup all looks correct. It took me a long time to figure out what was going on here, but it seems that fullscreen [doesn't work in inline mode](https://github.com/tinymce/tinymce-vue/issues/160#issuecomment-684520293). 

We use inline mode on all of our rich textareas to prevent separate iframes and CSS/JS requests for each field. This may just not be possible for us until the Vue-TinyMCE integration enables this feature.

**Comment by felixhelix** [comment]
Thanks a lot @NateWr for your help! So I guess we'll have to wait …

What about the working of fullscreen when using smarty templates: Why can't they be used for this pages also? Or, to pose the question differently, why is OJS applying two different approaches here?

Your's
Felix

P.S. Should I remove my pull request or do something about it?

**Comment by NateWr** [comment]
> What about the working of fullscreen when using smarty templates: Why can't they be used for this pages also? Or, to pose the question differently, why is OJS applying two different approaches here?

We're modernizing our approach to the UI. Our new forms use Vue.js and interact with the REST API we are building for OJS/OMP/OPS. The old forms will linger until we can modernize the whole UI.

I've closed the PR and I'll close this issue, but we can revisit this in the future if you'd like.
