### ISSUE TITLE
Failed Ajax request or invalid JSON returned

### ISSUE THREAD

**Issue by mariob2** [pkp/textEditorExtras#15]
PHP Fatal error:  Declaration of TextEditorExtrasSettingsForm::execute() must be compatible with Form::execute(...$functionArgs) in /var/www/html/site/plugins/generic/textEditorExtras/TextEditorExtrasSettingsForm.inc.php on line 65,

**Comment by mariob2** [comment]
already fixed sorry
https://github.com/pkp/pkp-lib/issues/8064 [Fix execute function signature](https://github.com/pkp/textEditorExtras/commit/46b8a7aa1acc8e6cbe1af780071d9f1ff2ef2d6d)

and 

https://github.com/pkp/pkp-lib/issues/8064 [Fix template array function on non-array](https://github.com/pkp/textEditorExtras/commit/528fea31178c5ca2d1bbaef5b74d455cea421a17)

**Comment by mpbraendle** [comment]
Hmm. Those patches are not available in the 1.0.0.4 version ...
