### ISSUE TITLE
Text Editor in the Plugin Gallery version

### ISSUE THREAD

**Issue by marlara** [pkp/textEditorExtras#16]
So, I have a bit of a problem here understanding what there is in the Plugin Gallery: following this issue https://github.com/pkp/pkp-lib/issues/8064#issuecomment-1182996378 I saw that the Text Editor has an italian locale here in github, which is not present in the Plugin Gallery version. I tried than to download the tar.gz from here (also to see if my issue gets resolved) but it gives me this error:

`ojs2: You are trying to downgrade the product "textEditorExtras" from version [1.0.0.4] to version [1.0.0.2]. Downgrades are not supported.`

Which is plausible. But I don't understand why in the Plugin Gallery there is a newer version with less locales (and where is it in github).

**Comment by NateWr** [comment]
Sorry @marlara this is my fault. I accidentally made the more recent releases from my own fork of this and everything needs to be synced up here. It's on my todo list. See: https://github.com/pkp/pkp-lib/issues/7537

As a general rule, only ever install from the plugin gallery to be sure you're getting a working release.

If you want the Italian locale, better to drop this file into place manually for now: https://github.com/pkp/textEditorExtras/tree/main/locale/it_IT
