### ISSUE TITLE
OJS 3.4 Compatibility

### ISSUE THREAD

**Issue by busspatrick** [pkp/textEditorExtras#24]
Hi all,

I work for the American Theological Library Association (Atla) and we've been using this plugin for years. Recently, I had to modify it in order to to be compatible with OJS 3.4. Although working off the v1_0_1-0 tag, I encountered some bugs, mainly with the settings form, so I hacked the template file (and a few others) to get it working. Any interest in this code? I'd be happy to push up my changes.

All the best

**Comment by johnywind** [comment]
Hey @busspatrick 
So great to hear that you fixed it. Can you share the code?

**Comment by busspatrick** [comment]
Hey @johnywind 
The changes are in PR #25 . Hope this helps

**Comment by asmecher** [comment]
Thanks -- and sorry for the long wait! Merged now.

**Comment by busspatrick** [comment]
@asmecher No problem. Thanks for your work.
